# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"
solc = "0.8.18"
src = "src"
test = "test"
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/',
  'hardhat/=node_modules/hardhat/',
]

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4
